### ISSUE TITLE
Ad Insertion content - Testcase 1 - Aligned content and period boundaries

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/Test-Content#1]
**A short description of the use case for the new test content.**
This test content is supposed to demonstrate the insertion of a midroll ad in a static MPD. In this testcase the segment- and period boundaries are perfectly aligned (as shown in the Figure below).

![Ad Insertion Testcases](https://user-images.githubusercontent.com/2427039/109485040-79eee000-7a81-11eb-8aaa-a66751a23dd1.png)

**Test content requirements**
* A multiperiod MPD with three periods
* Period 1 and 3 are continuous, Period 2 is an ad period
* Segment and period boundaries shall be aligned. For instance, audio and video segments can be 1.92 seconds with 25fps and 48khz. The first period might end at 9.6 seconds.
* The duration of each period is no longer than 10 seconds.
* All periods contain a single video and a single audio AdaptationSet.
* The content shall be encoded/packaged with CMAF and H.264 avc1
* Segment addressing should include at least:
  * `SegmentTemplate` with `$number$`
  * `SegmentTimeline` with `$number$` or `$time$` 
  * If possible: `SegmentBase`

**Relation to CTA WAVE Test Vector database**
* For the main content use Tears of Steel.
* For the ad test content use Big Buck Bunny.

**Comment by haudiobe** [comment]
TaC 2021/03/02:
- Conforming to DASH-IF Ad Insertion:  https://dash-industry-forum.github.io/docs/CR-Ad-Insertion-r8.pdf
- IF-5 conforming
- Follow the MPD Proxy Operation Guidelines in 8.2.7.3
- Follow the "urn:mpeg:dash:profile:cmaf:2019" profile
- also audio follows the same conditions as video

**Comment by TobbeEdgeware** [comment]
The proposed content is 24Hz. I'd suggest to convert to 25Hz in order to get same frame rate as used for live including the nx1.92s segment duration.

**Comment by haudiobe** [comment]
:dash

**Comment by jpiesing** [comment]
@juhajoki @murmur This looks very like what you are working on ....

**Comment by Murmur** [comment]
@jpiesing this is `a static mpd manifest` I believe, meaning all `<Period>` elements are available on initial manifest load. No `type=dynamic` refresh events, no injection of new periods at runtime on new mdp reload event. 

This topic still gives good details about the alignments, such as video(h264) an audio(aac) segments to have an equal perfect segment durations. This is something not easy to get with an integer 2,3,4,.. sec segments for aac codec. 
`AAC audio frame samples is 1024 per packet`

**Comment by rbouqueau** [comment]
Here are some streams to start with:
- https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/real/ad-insertion-testcase1.mpd
- https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/counter/ad-insertion-testcase1.mpd

Only the synthetic counter version plays well in dash.js at the moment.

**Comment by rbouqueau** [comment]
I could improve the generation process. Here is a new batch of files. 

Configurations:
  a. one encoder for the main content, one encoder for the ad content
   b. different encoders
   c. one encoder for the 3 periods (counter content only)

Counter:
a. (known issue on first period duration) https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/counter/a/ad-insertion-testcase1.mpd
a. https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/counter/b/ad-insertion-testcase1.mpd
a. https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/counter/c/ad-insertion-testcase1.mpd

Real (ToS+BBB):
a. https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/real/a/ad-insertion-testcase1.mpd
b. https://reference.dashif.org/dash.js/v4.0.0-alpha/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/real/b/ad-insertion-testcase1.mpd

I'm still working on it.

**Comment by Murmur** [comment]
Is it a mistake to have `<BaseURL>https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch2/counter/b/ad-insertion-testcase1.mpd</BaseURL>` value ending to a manifest.mpd as well?

Can you provide your ffmpeg+mp4box command lines for creating this content such as CMAF and 1.92s segmenting?

**Comment by rbouqueau** [comment]
> Is it a mistake

Yes, thanks for reporting!

> Can you provide your ffmpeg+mp4box command lines for creating this content such as CMAF and 1.92s segmenting?

See here https://github.com/Dash-Industry-Forum/Test-Content/blob/e31b16f3fd188b00988de2906910f40c23fb98e2/ad-insertion-testcase1.sh. I've just created the PR.

NB1: it uses one-liner commands using GPAC only (wherever possible).

NB2: the refresh time of the server is quite long. So fixes may take time to apply.

**Comment by rbouqueau** [comment]
Comment from today's call: favour this client version: https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

**Comment by dsilhavy** [comment]
I did a check in dash.js and Shaka, please find the test results and observations here:
https://docs.google.com/spreadsheets/d/1OLRzskFmO5yL_kJpF6cILrO_uy-USrTmvsWZHEgqgtw/edit

**Comment by Murmur** [comment]
We have done this multiperiod(main content, adverts, static mpd) a little over a year ago. We also test `manifest events` on this one. Feel free to test run but nightly build most likely stalled at 1m55s in a main content(after first adverts, see burn-in timestamp).
https://refapp.hbbtv.org/videos/00_llama_multiperiod_v1/manifest.mpd
https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

We are compiling a similar scenario for a dynamic(live) test content.

**Comment by rbouqueau** [comment]
@dsilhavy the @MediaPresentationDuration was not referenced in the document but is fixed. Still working on the other items.

**Comment by rbouqueau** [comment]
@dsilhavy I checked the duration of the periods and they seem ok.

To dump the mpd as a file I used ```gpac -i URL.mpd -o file.mp4```. And I used ```MP4Box -info``` to inspect the durations.

I'm going to generate a new batch of files soon.

The other mandatory points should be fixed so I generated a batch3:

**Comment by rbouqueau** [comment]
- https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/counter/a/ad-insertion-testcase1.mpd
- https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/counter/b/ad-insertion-testcase1.mpd
- https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/counter/c/ad-insertion-testcase1bis.mpd
- https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/real/a/ad-insertion-testcase1.mpd
- https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/real/b/ad-insertion-testcase1.mpd

**Comment by dsilhavy** [comment]
@rbouqueau Thanks for the new vectors, I added a second tab to the Spreadsheet: https://docs.google.com/spreadsheets/d/1OLRzskFmO5yL_kJpF6cILrO_uy-USrTmvsWZHEgqgtw/edit#gid=498241230

Overall it looks good, I see a minor problem in dash.js having a small gap in the end for all testvectors. 

https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch4/real/a/ad-insertion-testcase1.mpd has a major issue between period 2 and 3 in both dash.js and Shaka. Might be related to differences between PTO and tfdt->bmdt in the audio segments.

**Comment by rbouqueau** [comment]
I think I fixed the real/a content: https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/real/a/ad-insertion-testcase1.mpd

To summarize, since the AUs boundaries are exactly where we cut the Periods, working in the encoded or raw domain shouldn't make any difference. But it does so I switched to raw.

I also applied the same patch in an attempt to fix the ```Jumping to end of stream because of gap from 28.677133 to 28.8. Gap duration: 0.1228669999999994``` messages. I'd be happy if we could have a look together at what's happening. An inspection of the content shows that the durations seem fine but I may be missing something.

**Comment by dsilhavy** [comment]
@rbouqueau Thanks for the feedback.

Regarding gap jumping:

Jumping to end of stream because of gap from 28.677133 to 28.8. Gap duration: 0.1228669999999994
 
The problem was that we did not call MSE.endOfStream if the last period was prebuffered once the previous period is still playing. This fixed here https://github.com/Dash-Industry-Forum/dash.js/commit/a1297a26949759ca0aee4f648a253a70727fa192 . Changes should be visible in nightly.

**Comment by rbouqueau** [comment]
Batch5:

- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/counter/a/ad-insertion-testcase1.mpd
- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/counter/b/ad-insertion-testcase1.mpd
- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/counter/c/ad-insertion-testcase1.mpd
- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/real/a/ad-insertion-testcase1.mpd
- https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/dashif/ad-insertion-testcase1/batch5/real/b/ad-insertion-testcase1.mpd

Seems like the logs are happy. I'm seeing something that looks like a clock rectification between Periods #2 and #3 on counter/b (second link). Can you see it also?

**Comment by rbouqueau** [comment]
We can remove the following labels after comments in the CTA-WAVE DTCTF call today:

- missing-CMAF-content
- missing-mezzanine

Once I get access to the appropriate information on the Interoperability WG I assume I'll have to regenerate the vectors.

**Comment by haudiobe** [comment]
Test content is good - needs to be published and announced, please add to data base.

**Comment by rbouqueau** [comment]
Added to database: https://testassets.dashif.org/#testcase/details/61681dfa06d983046b7d4140

**Comment by haudiobe** [comment]
Test Call 2021/11/12:
- @rbouqueau thanks

**Comment by haudiobe** [comment]
This one is available - announce to DASH-IF IOP
