### ISSUE TITLE
Use https for WebVTT sample

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/Test-Content#7]
**Describe the bug**
The teststream for WebVTT https://dash.akamaized.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd used an http link as `BaseURL`:

`<BaseURL>http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/ElephantsDream_en.vtt</BaseURL> `

 Since the MPD is available via https this caused mixed content issues in the browser. 

**Expected behavior**
Please change the BaseURL to https if possible. The subtitle file might be hosted on https://dash.akamaized.net, similar to the MPD.

**Comment by rbouqueau** [comment]
This was fixed on June 21st already: https://dash.akamaized.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1_https.mpd

@dsilhavy check and close if ok!

**Comment by dsilhavy** [comment]
@rbouqueau Perfect, works thanks
